WIDTH = 1700
HEIGHT = 800

LENGTH = 250
EPOCHS = 150

CELL_WIDTH = CELL_HEIGHT = min(WIDTH // LENGTH, HEIGHT // EPOCHS)

LINE_WIDTH = CELL_WIDTH * LENGTH
LINE_HEIGHT = CELL_HEIGHT

WIDTH = LINE_WIDTH
HEIGHT = LINE_HEIGHT * EPOCHS
